;;; generate-large-fixture.el --- Generate a Magic LaTeX stress fixture -*- lexical-binding: t; -*-

;; SPDX-License-Identifier: GPL-2.0-or-later
;;
;; This file is not part of GNU Emacs.

;;; Commentary:

;; Generate a deterministic, non-personal LaTeX document which exercises the
;; display features used by Magic LaTeX.  Run from the repository root:
;;
;;   emacs -Q --batch -l test/generate-large-fixture.el -- \
;;     test/fixtures/large-document.tex 128

;;; Code:

(defconst ml-test/fixture-fragment
  (concat
   "\\section{Synthetic section %d}\n"
   "This deterministic paragraph contains \\textbf{bold text}, "
   "\\emph{emphasized text}, and \\texttt{fixed-width text}.\n"
   "The model is $y_i = \\alpha + \\beta x_i + \\epsilon_i$ with "
   "$\\sigma^2 = \\frac{1}{n} \\sum_{i=1}^{n}(x_i-\\mu)^2$.\n"
   "Relations include $x \\leq y$, $x \\neq z$, $u \\in \\mathbb{R}$, "
   "and $A \\rightarrow B \\Rightarrow C$.\n"
   "Accents include $\\vec{x}$, $\\hat{y}$, $\\tilde{z}$, "
   "$\\bar{q}$, and $\\dot{r}$.\n"
   "{\\large A large block with {\\bfseries nested bold text} and "
   "{\\color{blue} a nested color block}.}\n"
   "\\begin{align}\n"
   "  \\mathbb{E}[Y \\mid X] &= \\alpha + \\beta X \\\\\n"
   "  \\operatorname{Var}(Y) &= \\sigma^2 + \\tau^2\n"
   "\\end{align}\n"
   "\\begin{itemize}\n"
   "\\item A nested value $a_{b_c}^{d^e}$ and escaped text \\%% \\$ \\&.\n"
   "\\item Spacing commands appear here: thin\\,space, wide\\;space, "
   "and a nonbreaking~space.\n"
   "\\end{itemize}\n"
   "%% Ignored comment symbols: \\alpha \\sum \\rightarrow \\mathbb{R}.\n"
   "\\begin{verbatim}\n"
   "\\alpha \\sum \\vec{x} should remain literal here.\n"
   "\\end{verbatim}\n\n")
  "Repeated source fragment for the generic performance fixture.")

(defun ml-test/generate-large-fixture (output kib)
  "Write a deterministic LaTeX fixture of approximately KIB KiB to OUTPUT."
  (let ((target (* kib 1024))
        (index 1))
    (make-directory (file-name-directory output) t)
    (with-temp-file output
      (insert
       "%% Generated by test/generate-large-fixture.el; do not edit manually.\n"
       "\\documentclass{article}\n"
       "\\usepackage{amsmath,amssymb,xcolor}\n"
       "\\title{Generic Magic LaTeX Performance Fixture}\n"
       "\\begin{document}\n"
       "\\maketitle\n\n")
      (while (< (buffer-size) target)
        (insert (format ml-test/fixture-fragment index))
        (setq index (1+ index)))
      (insert "\\end{document}\n"))))

(when noninteractive
  (when (equal (car command-line-args-left) "--")
    (pop command-line-args-left))
  (let ((output (or (pop command-line-args-left)
                    "test/fixtures/large-document.tex"))
        (kib (string-to-number
              (or (pop command-line-args-left) "128"))))
    (ml-test/generate-large-fixture (expand-file-name output) kib)))

;;; generate-large-fixture.el ends here
